sudo: false
language: go
dist: trusty
go:
    - 1.x
    - 1.8.x
    - 1.7.x
    - 1.6.x
    - tip
before_install:
    - go get github.com/tools/godep
    - go get github.com/davecgh/go-spew/spew
    - go get github.com/k0kubun/pp
    - go get github.com/mattn/goveralls
    - go get golang.org/x/tools/cmd/cover
    - go get github.com/modocache/gover
    - go get github.com/golang/lint/golint
    - godep restore
    - sudo apt-get update -qq
    - sudo apt-get install -y openssl libcppunit-dev libreadline6 libreadline6-dev valgrind realpath libmodule-install-perl
    - git clone https://github.com/yahoo/mdbm.git src_mdbm
before_script:
    - cd src_mdbm/
    - make -j2 
    - make install
    - cd ..
script:
    - make test
    - make coveralls
matrix:
    allow_failures:
        - go: tip
          fast_finish: true
