sudo: false
language: go
go:
    - 1.x
    - 1.9.x
    - 1.8.x
    - 1.7.x
    - 1.6.x
before_install:
    - go get github.com/tools/godep
    - godep restore
    - sudo apt-get update -qq
    - sudo apt-get install -y openssl libcppunit-dev libreadline6 libreadline6-dev valgrind realpath libmodule-install-perl
    - sudo dpkg -i pkg/ubuntu/mdbm-Trusty_Tahr.deb
#    - git clone https://github.com/yahoo/mdbm.git src_mdbm
#before_script:
#    - cd src_mdbm/
#    - make -j2 
#    - make install
#    - cd ..
script:
    - make installpkgs
    - make metalinter
    - make test
    - make coveralls
