sudo: required 
language: go
go:
    - 1.9.x
    - 1.8.x
    - 1.7.x
    - 1.6.x
    - 1.5.x
    - 1.4.x
before_install:
    - sudo go get github.com/tools/godep
    - sudo go get github.com/davecgh/go-spew/spew
    - sudo go get github.com/k0kubun/pp
    - sudo go get github.com/mattn/goveralls
    - sudo go get golang.org/x/tools/cmd/cover
    - sudo go get github.com/modocache/gover
    - sudo godep restore
    - sudo apt-get update -qq
    - sudo apt-get install -y openssl libcppunit-dev libreadline6 libreadline6-dev valgrind realpath libmodule-install-perl
    - sudo dpkg -i pkg/ubuntu/mdbm-Trusty_Tahr.deb
#    - git clone https://github.com/yahoo/mdbm.git src_mdbm
#before_script:
#    - cd src_mdbm/
#    - make -j2 
#    - make install
#    - cd ..
script:
    - sudo make installpkgs
    - sudo make metalinter
    - sudo make test
    - sudo make coveralls
