sudo: false
language: go
dist: trusty
go:
    - 1.x
    - 1.8.x
    - 1.7.x
    - 1.6.x
    - 1.5.x
    - 1.4.x
    - tip
before_install:
    - go get github.com/tools/godep
    - godep restore
    - sudo apt-get update -qq
    - sudo apt-get install -y openssl libcppunit-dev libreadline6 libreadline6-dev valgrind realpath libmodule-install-perl
before_script:
    - perl -pi -e 's/\/tmp\/install\//\.\/.prebuild-mdbm\/ubuntu\//g' mdbm.go
script:
    - make test
    - make coveralls
matrix:
    allow_failures:
        - go: tip
          fast_finish: true
